creating a view and controller
wolox-training/fm-java pull request #1
Opened 2022-01-12 23:17 UTC by f-medina

## Summary
- First Controller and view
## Trello Card
https://trello.com/c/SwF8ZkMh/17-crear-un-controller-y-una-vista-de-bienvenida

2022-01-12 23:59 UTC, torsello requested changes
Some comments :)

2022-01-12 23:59 UTC, torsello commented on src/main/java/wolox/training/controllers/GreetingController.java
> +    public String greeting(@RequestParam(name="name", required=false, defaultValue="World") String name, @NotNull Model model) {
In this case, you are using 'name' and 'greeting' more than one time.

It's always a good practice to extract this strings on a constant, to reuse it.

2022-01-13 14:16 UTC, AleFalcon approved these changes
With the comment from Matias, it's ok this PR.

Good job.

2022-01-17 20:01 UTC, torsello approved these changes
LGTM!

2022-01-17 20:01 UTC, torsello commented on src/main/java/wolox/training/controllers/GreetingController.java
> +    public String greeting(@RequestParam(name=NAME, required=false, defaultValue="World") String name, @NotNull Model model) {
You must extract "World" and "greeting" on constants too :)

2022-01-18 14:26 UTC, merged