Feature/book model
wolox-training/fm-java pull request #2
Opened 2022-01-17 19:08 UTC by f-medina

## Summary
- Completed the book Model
## Trello Card
https://trello.com/c/L7vbnY7H/14-crear-modelo-de-book

2022-01-17 19:35 UTC, AleFalcon requested changes

2022-01-17 19:35 UTC, AleFalcon commented on src/main/java/wolox/training/models/Book.java
> +
You must create empty constructor. This constructor's used by JPA by default

2022-01-17 20:05 UTC, torsello requested changes
I'm with Ale, you must create an empty constructor too.

Fran, are you using a .gitignore file? if not, please add one for intellij + java + gradle.

2022-01-20 13:40 UTC, torsello commented on src/main/java/wolox/training/models/Book.java
> +    public Book() {
Fran, after pushing your fixes, please click on request review again :)

2022-01-20 13:40 UTC, torsello approved these changes
LGTM!

2022-01-24 19:44 UTC, AleFalcon approved these changes

2022-01-25 18:19 UTC, merged